// GENERATED by design-tokens/build.py from tokens.json. Do not edit.
package app.pane.android.ui.theme.tokens

import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.ui.unit.dp

object PaneDimens {
    /** proposed */ val Space2 = 2.dp
    /** proposed */ val Space4 = 4.dp
    /** proposed */ val Space8 = 8.dp
    /** proposed */ val Space12 = 12.dp
    /** proposed */ val Space16 = 16.dp
    /** proposed */ val Space20 = 20.dp
    /** proposed */ val Space24 = 24.dp
    /** proposed */ val Space32 = 32.dp
    /** locked */ val SizeTouchMin = 48.dp
    /** locked */ val SizeChip = 36.dp
    /** locked */ val SizeChipRow = 52.dp
    /** locked */ val SizeChipGap = 8.dp
    /** locked */ val SizeScreenInset = 16.dp
    /** locked */ val SizeButtonTall = 52.dp
    /** locked */ val SizeExitTile = 48.dp
    /** locked */ val SizeAvatarHeader = 40.dp
    /** locked */ val SizeAvatarComment = 32.dp
    /** locked */ val SizeAvatarHistory = 30.dp
    /** locked */ val SizeThumbHistory = 42.dp
    /** locked */ val SizeToggleWidth = 52.dp
    /** locked */ val SizeToggleHeight = 32.dp
    /** locked */ val SizeFocusRing = 2.dp
    /** proposed */ val SizeIcon = 24.dp
}

object PaneShapes {
    /** locked */ val washInline = RoundedCornerShape(5.dp)
    /** locked */ val focus = RoundedCornerShape(4.dp)
    /** locked */ val rowWash = RoundedCornerShape(12.dp)
    /** locked */ val exitTile = RoundedCornerShape(14.dp)
    /** locked */ val rowHeld = RoundedCornerShape(14.dp)
    /** locked */ val tile = RoundedCornerShape(16.dp)
    /** locked */ val card = RoundedCornerShape(18.dp)
    /** locked */ val chip = RoundedCornerShape(18.dp)
    /** locked */ val sheet = RoundedCornerShape(20.dp)
    /** locked */ val pill = RoundedCornerShape(999.dp)
}

object PaneMotion {
    /** locked */ const val OpacityWashInk = 0.06f
    /** locked */ const val OpacityWashSlate = 0.16f
    /** locked */ const val OpacityChipCoralTint = 0.17f
    /** locked */ const val PressFadeMs = 150
    /** proposed */ val EasingStandard = androidx.compose.animation.core.CubicBezierEasing(0f, 0f, 0.2f, 1f)
    /** from-code */ const val FastMs = 120
    /** from-code */ const val MediumMs = 220
    /** from-code */ const val SlowMs = 300
    /** proposed */ const val ControlsAutohideMs = 3000
}
