// GENERATED by design-tokens/build.py from tokens.json. Do not edit.
package app.pane.android.ui.theme.tokens

import androidx.compose.ui.graphics.Color

object PaneTokenColors {
    /** locked */ val Night = Color(0xFF0E0B0A)
    /** locked */ val Raised = Color(0xFF191412)
    /** locked */ val RaisedPressed = Color(0xFF26211F)
    /** locked */ val NightPressed = Color(0xFF1C1917)
    /** locked */ val Ink = Color(0xFFF4EFEA)
    /** locked */ val InkSoft = Color(0xFFDAD4CE)
    /** locked */ val Mute = Color(0xFF8A827A)
    /** locked */ val Edge = Color(0xFF262018)
    /** locked */ val Coral = Color(0xFFD4886A)
    /** locked */ val Slate = Color(0xFF9DB4CC)
    /** locked */ val SlatePressed = Color(0xFFC3D2E1)
    /** locked */ val SlateWashNight = Color(0xFF252629)
    /** locked */ val SlateWashRaised = Color(0xFF2E2E30)
    /** from-code */ val Mint = Color(0xFF5BA8A0)
    /** locked */ val ColorBgDefault = Color(0xFF0E0B0A)
    /** locked */ val ColorBgRaised = Color(0xFF191412)
    /** locked */ val ColorBgPressedOnNight = Color(0xFF1C1917)
    /** locked */ val ColorBgPressedOnRaised = Color(0xFF26211F)
    /** locked */ val ColorTextPrimary = Color(0xFFF4EFEA)
    /** locked */ val ColorTextSoft = Color(0xFFDAD4CE)
    /** locked */ val ColorTextMeta = Color(0xFF8A827A)
    /** locked */ val ColorTextHandle = Color(0xFF9DB4CC)
    /** locked */ val ColorTextHandlePressed = Color(0xFFC3D2E1)
    /** locked */ val ColorTextOnAccent = Color(0xFF0E0B0A)
    /** locked */ val ColorBorderHairline = Color(0xFF262018)
    /** locked */ val ColorAccentExit = Color(0xFFD4886A)
    /** proposed */ val ColorAccentExitPressed = Color(0xFFC27A5F)
    /** from-code */ val ColorStatusSuccess = Color(0xFF5BA8A0)
}
