// GENERATED by design-tokens/build.py from tokens.json. Do not edit.
package app.pane.android.ui.theme.tokens

import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.em
import androidx.compose.ui.unit.sp

// Families come from the app: PaneDisplay (Inter Tight) and Inter (Inter), see ui/theme/Type.kt.
object PaneTokenType {
    /** locked */ fun Display(display: FontFamily, text: FontFamily) = TextStyle(fontFamily = display, fontWeight = FontWeight(500), fontSize = 44.sp, lineHeight = 48.4.sp, letterSpacing = (-0.025).em)
    /** locked */ fun TitlePage(display: FontFamily, text: FontFamily) = TextStyle(fontFamily = display, fontWeight = FontWeight(600), fontSize = 22.sp, lineHeight = 27.5.sp, letterSpacing = (0.0).em)
    /** locked */ fun Title(display: FontFamily, text: FontFamily) = TextStyle(fontFamily = text, fontWeight = FontWeight(600), fontSize = 26.sp, lineHeight = 32.5.sp, letterSpacing = (0.0).em)
    /** locked */ fun Body(display: FontFamily, text: FontFamily) = TextStyle(fontFamily = text, fontWeight = FontWeight(400), fontSize = 17.sp, lineHeight = 24.6.sp, letterSpacing = (0.0).em)
    /** locked */ fun BodyDetail(display: FontFamily, text: FontFamily) = TextStyle(fontFamily = text, fontWeight = FontWeight(400), fontSize = 15.sp, lineHeight = 21.8.sp, letterSpacing = (0.0).em)
    /** locked */ fun Label(display: FontFamily, text: FontFamily) = TextStyle(fontFamily = text, fontWeight = FontWeight(600), fontSize = 15.sp, lineHeight = 19.5.sp, letterSpacing = (0.0).em)
    /** locked */ fun Meta(display: FontFamily, text: FontFamily) = TextStyle(fontFamily = text, fontWeight = FontWeight(400), fontSize = 13.sp, lineHeight = 17.6.sp, letterSpacing = (0.0).em)
}
