#!/usr/bin/env python3
"""Generate Android (Compose + XML) and web (CSS) exports from tokens.json. Usage: python3 build.py"""
import json, os, re
H=os.path.dirname(os.path.abspath(__file__)); T=json.load(open(f"{H}/tokens.json"))
def walk(n,p=()):
    if "$value" in n: yield p,n; return
    for k,v in n.items():
        if not k.startswith("$"): yield from walk(v,p+(k,))
def get(path):
    n=T
    for k in path.split("."): n=n[k]
    return n
def res(v):
    if isinstance(v,str) and re.fullmatch(r"\{[^}]+\}",v): return res(get(v[1:-1])["$value"])
    if isinstance(v,dict): return {k:res(x) for k,x in v.items()}
    return v
toks=[(p,n,res(n["$value"])) for p,n in walk(T)]
st=lambda n:n["$extensions"]["app.pane"]["status"]
camel=lambda p:"".join(w[:1].upper()+w[1:] for s in p for w in re.split(r"[-.]",s))
num=lambda v:float(str(v).rstrip("pxms"))
fmt=lambda f:(str(int(f)) if f==int(f) else str(f))
hdr="// GENERATED by design-tokens/build.py from tokens.json. Do not edit.\n"
os.makedirs(f"{H}/android/compose",exist_ok=True); os.makedirs(f"{H}/android/res/values",exist_ok=True); os.makedirs(f"{H}/web",exist_ok=True)
pk="package app.pane.android.ui.theme.tokens\n\n"
# Color.kt
L=[hdr+pk+"import androidx.compose.ui.graphics.Color\n\nobject PaneTokenColors {"]
for p,n,v in toks:
    if n["$type"]=="color": L.append(f"    /** {st(n)} */ val {camel(p[2:] if p[0]=='primitive' else p[1:])} = Color(0xFF{v[1:].upper()})")
L.append("}");open(f"{H}/android/compose/PaneTokenColors.kt","w").write("\n".join(L)+"\n")
# Type.kt
L=[hdr+pk+"import androidx.compose.ui.text.TextStyle\nimport androidx.compose.ui.text.font.FontFamily\nimport androidx.compose.ui.text.font.FontWeight\nimport androidx.compose.ui.unit.em\nimport androidx.compose.ui.unit.sp\n",
 "// Families come from the app: PaneDisplay (Inter Tight) and Inter (Inter), see ui/theme/Type.kt.","object PaneTokenType {"]
for p,n,v in toks:
    if n["$type"]=="typography":
        fam="display" if "Tight" in v["fontFamily"][0] else "text"
        fs=num(v["fontSize"]); ls=float(v["letterSpacing"].rstrip("em"))
        L.append(f"    /** {st(n)} */ fun {camel(p[2:])}(display: FontFamily, text: FontFamily) = TextStyle(fontFamily = {fam}, fontWeight = FontWeight({v['fontWeight']}), fontSize = {fmt(fs)}.sp, lineHeight = {fmt(round(fs*v['lineHeight'],1))}.sp, letterSpacing = ({ls}).em)")
L.append("}");open(f"{H}/android/compose/PaneTokenType.kt","w").write("\n".join(L)+"\n")
# Dimens/Shape/Motion
L=[hdr+pk+"import androidx.compose.foundation.shape.RoundedCornerShape\nimport androidx.compose.ui.unit.dp\n\nobject PaneDimens {"]
for p,n,v in toks:
    if n["$type"]=="dimension" and p[-2] in("space","size"): L.append(f"    /** {st(n)} */ val {camel((p[-2],p[-1]))} = {fmt(num(v))}.dp")
L+=["}","","object PaneShapes {"]
for p,n,v in toks:
    if p[1]=="radius": L.append(f"    /** {st(n)} */ val {camel(p[-1:])[0].lower()+camel(p[-1:])[1:]} = RoundedCornerShape({fmt(num(v))}.dp)")
L+=["}","","object PaneMotion {"]
for p,n,v in toks:
    if p[1]=="motion" or p[-2]=="opacity":
        if n["$type"]=="duration": L.append(f"    /** {st(n)} */ const val {camel(p[-1:])}Ms = {int(num(v))}")
        elif n["$type"]=="cubicBezier": L.append(f"    /** {st(n)} */ val {camel(p[-1:])} = androidx.compose.animation.core.CubicBezierEasing({', '.join(str(x)+'f' for x in v)})")
        else: L.append(f"    /** {st(n)} */ const val {camel(p[-2:])} = {v}f")
L.append("}");open(f"{H}/android/compose/PaneTokenDimens.kt","w").write("\n".join(L)+"\n")
# XML
X=['<?xml version="1.0" encoding="utf-8"?>',"<!-- GENERATED by design-tokens/build.py. Do not edit. -->","<resources>"]
for p,n,v in toks:
    nm="pane_"+"_".join(p[1:]).replace("-","_").replace(".","_")
    if n["$type"]=="color": X.append(f'    <color name="{nm}">{v}</color> <!-- {st(n)} -->')
    elif n["$type"]=="dimension": X.append(f'    <dimen name="{nm}">{fmt(num(v))}dp</dimen> <!-- {st(n)} -->')
    elif n["$type"]=="duration": X.append(f'    <integer name="{nm}">{int(num(v))}</integer> <!-- {st(n)} -->')
X.append("</resources>");open(f"{H}/android/res/values/pane_tokens.xml","w").write("\n".join(X)+"\n")
# CSS
C=["/* GENERATED by design-tokens/build.py from tokens.json. Do not edit. Dark-only (sources define no light palette). */",":root {","  color-scheme: dark;"]
var=lambda p:"--pane-"+"-".join(p[1:] if p[0]=="semantic" else p).replace(".","-")
for p,n,v in toks:
    ty=n["$type"]; raw=n["$value"]; s=st(n)
    if ty=="typography":
        b=var(p); fam=", ".join(f'"{f}"' if " " in f else f for f in v["fontFamily"])
        C+= [f"  {b}-family: {fam};",f"  {b}-weight: {v['fontWeight']};",f"  {b}-size: {num(v['fontSize'])/16:g}rem; /* {v['fontSize']} */",f"  {b}-line-height: {v['lineHeight']};",f"  {b}-letter-spacing: {v['letterSpacing']}; /* {s} */"]; continue
    if isinstance(raw,str) and raw.startswith("{"): val=f"var({var(tuple(raw[1:-1].split('.')))})"
    elif ty=="fontFamily": val=", ".join(f'"{f}"' if " " in f else f for f in v)
    elif ty=="cubicBezier": val=f"cubic-bezier({', '.join(map(str,v))})"
    else: val=v
    C.append(f"  {var(p)}: {val}; /* {s} */")
C.append("}");open(f"{H}/web/tokens.css","w").write("\n".join(C)+"\n")
print("built:",len(toks),"tokens")
